---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chatxvyt/repositories/chatPGT_/
    
    - /bin/cp -R * $DEPLOYPATH

    # 3) activate the virtualenv cPanel created and install deps
    - source /home/chatxvyt/virtualenv/chatPGT_/3.*/bin/activate && \
      pip install -r $DEPLOYPATH/requirements.txt

    # 4) touch WSGI entry so Passenger reloads your Flask app
    - touch $DEPLOYPATH/passenger_wsgi.py
