---
deployment:
  tasks:
    # 1) adjust this to your cPanel username and your app’s root folder
    - export CPUSER=mahanabba
    - export APPROOT=/home/$CPUSER/chatPGT_

    # 2) copy everything from the Git checkout into the Python App root
    - /bin/cp -R * $APPROOT

    # 3) activate the virtualenv cPanel created and install deps
    - source /home/$CPUSER/virtualenv/chatPGT_/3.*/bin/activate && \
      pip install -r $APPROOT/requirements.txt

    # 4) touch WSGI entry so Passenger reloads your Flask app
    - touch $APPROOT/passenger_wsgi.py
